
/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the plugin repository
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => PrettyReaderPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian4 = require("obsidian");

// src/document.ts
var import_obsidian = require("obsidian");

// src/types.ts
var PRETTY_READER_VIEW_TYPE = "pretty-reader-view";
var LAYOUT_OPTIONS = ["article", "paper", "cards"];
var THEME_OPTIONS = [
  "warm-paper",
  "graphite",
  "clean-sky"
];
var COLUMN_MODE_OPTIONS = ["single", "double"];
var DEFAULT_SETTINGS = {
  defaultLayout: "article",
  defaultTheme: "warm-paper",
  exportDirectory: "exports/pretty-reader",
  notePreferences: {}
};
function supportsColumnMode(layout) {
  return layout === "article" || layout === "paper";
}

// src/document.ts
var IMAGE_EXTENSIONS = /* @__PURE__ */ new Set([
  "avif",
  "bmp",
  "gif",
  "jpeg",
  "jpg",
  "png",
  "svg",
  "webp"
]);
async function buildPrettyReaderDocument(app, file, settings) {
  const rawMarkdown = await app.vault.cachedRead(file);
  const contentWithoutFrontmatter = stripFrontmatter(rawMarkdown).trim();
  const frontmatter = app.metadataCache.getFileCache(file)?.frontmatter ?? {};
  const leadingTitleHeading = extractFirstLevelOneHeading(contentWithoutFrontmatter);
  const displayMarkdown = stripLeadingTitleHeading(
    contentWithoutFrontmatter,
    leadingTitleHeading?.text
  ).trim();
  const title = readString(frontmatter.title) ?? leadingTitleHeading?.text ?? file.basename;
  const subtitle = readString(frontmatter.subtitle);
  const author = readString(frontmatter.author);
  const layout = parseLayout(frontmatter.pretty, settings.defaultLayout);
  const notePreference = settings.notePreferences[file.path] ?? {};
  const theme = parseTheme(
    notePreference.theme ?? frontmatter.theme,
    settings.defaultTheme
  );
  const columnMode = parseColumnMode(notePreference.columnMode, layout);
  const toc = parseBoolean(frontmatter.toc, false);
  const coverReference = readString(frontmatter.cover);
  const cover = coverReference ? resolveResourceReference(app, file, coverReference, "cover") ?? void 0 : void 0;
  const resources = collectResources(app, file, displayMarkdown, cover);
  const exportMarkdown = rewriteMarkdownForExport(
    app,
    file,
    displayMarkdown,
    resources
  );
  const headings = assignAnchors(extractHeadings(displayMarkdown));
  const cards = splitMarkdownIntoCards(displayMarkdown);
  const exportCards = splitMarkdownIntoCards(exportMarkdown);
  const wordCount = estimateReadableUnits(displayMarkdown);
  const readingMinutes = Math.max(1, Math.ceil(wordCount / 320));
  const updatedLabel = formatUpdatedAt(file.stat.mtime);
  return {
    file,
    filePath: file.path,
    title,
    subtitle: subtitle ?? void 0,
    author: author ?? void 0,
    layout,
    theme,
    columnMode,
    toc,
    wordCount,
    readingMinutes,
    updatedLabel,
    rawMarkdown,
    displayMarkdown,
    exportMarkdown,
    headings,
    cards,
    exportCards,
    cover,
    resources
  };
}
function normalizeExportDirectory(input) {
  const trimmed = input.trim().replace(/^\/+/, "");
  return (0, import_obsidian.normalizePath)(trimmed || "exports/pretty-reader");
}
function noteSlug(filePath) {
  const cleanPath = filePath.replace(/\\/g, "/");
  const baseName = cleanPath.split("/").pop() ?? cleanPath;
  const stem = baseName.replace(/\.[^.]+$/, "");
  const readable = toAsciiSlug(stem) || "note";
  const hash = Buffer.from(cleanPath, "utf8").toString("base64url").slice(0, 8);
  return `${readable}-${hash}`;
}
function assetExportHref(resource) {
  if (resource.isExternal) {
    return resource.externalUrl ?? null;
  }
  if (!resource.assetFileName) {
    return null;
  }
  return `./assets/${encodeURIComponent(resource.assetFileName)}`;
}
async function ensureFolder(app, folderPath) {
  const normalized = (0, import_obsidian.normalizePath)(folderPath);
  const segments = normalized.split("/").filter(Boolean);
  let currentPath = "";
  for (const segment of segments) {
    currentPath = currentPath ? `${currentPath}/${segment}` : segment;
    const exists = await app.vault.adapter.exists(currentPath);
    if (!exists) {
      await app.vault.adapter.mkdir(currentPath);
    }
  }
}
function collectResources(app, file, markdown, cover) {
  const resources = /* @__PURE__ */ new Map();
  const addResource = (resource) => {
    if (!resource) {
      return;
    }
    const key = resource.resolvedPath ? `local:${resource.resolvedPath}` : `external:${resource.reference}`;
    if (resources.has(key)) {
      return;
    }
    if (!resource.isExternal && resource.resolvedPath) {
      resource.assetFileName = makeAssetFileName(resource.resolvedPath);
    }
    resources.set(key, resource);
  };
  addResource(cover);
  for (const reference of extractImageReferences(markdown)) {
    addResource(resolveResourceReference(app, file, reference, "image"));
  }
  return Array.from(resources.values());
}
function rewriteMarkdownForExport(app, file, markdown, resources) {
  const resourceByPath = new Map(
    resources.filter((resource) => resource.resolvedPath).map((resource) => [resource.resolvedPath, resource])
  );
  const resolveExportTarget = (reference) => {
    if (isExternalUrl(reference)) {
      return reference;
    }
    const resolved = resolveResourceReference(app, file, reference, "image");
    if (!resolved) {
      return null;
    }
    if (resolved.isExternal) {
      return resolved.externalUrl ?? null;
    }
    if (!resolved.resolvedPath) {
      return null;
    }
    const existing = resourceByPath.get(resolved.resolvedPath) ?? resolved;
    return assetExportHref(existing);
  };
  let output = markdown.replace(/!\[\[([^\]]+)\]\]/g, (_match, inner) => {
    const { target } = parseWikiTarget(inner);
    const exportTarget = resolveExportTarget(target);
    const altText = target.split("/").pop()?.replace(/\.[^.]+$/, "") ?? "image";
    if (exportTarget) {
      return `![${altText}](${exportTarget})`;
    }
    return `*Missing image: ${altText}*`;
  });
  output = output.replace(/\[\[([^\]]+)\]\]/g, (_match, inner) => {
    const { target, alias } = parseWikiTarget(inner);
    return alias || target.split("#")[0];
  });
  output = output.replace(/!\[([^\]]*)\]\(([^)]+)\)/g, (match, alt, target) => {
    const parsedTarget = parseMarkdownTarget(target);
    if (isExternalUrl(parsedTarget)) {
      return match;
    }
    const exportTarget = resolveExportTarget(parsedTarget);
    if (!exportTarget) {
      return alt || "Missing image";
    }
    return `![${alt}](${exportTarget})`;
  });
  output = output.replace(
    /(?<!!)\[([^\]]+)\]\(([^)]+)\)/g,
    (match, text, target) => {
      const parsedTarget = parseMarkdownTarget(target);
      if (isExternalUrl(parsedTarget) || parsedTarget.startsWith("#")) {
        return match;
      }
      return text;
    }
  );
  return output;
}
function parseLayout(value, fallback) {
  return LAYOUT_OPTIONS.includes(value) ? value : fallback;
}
function parseTheme(value, fallback) {
  return THEME_OPTIONS.includes(value) ? value : fallback;
}
function parseColumnMode(value, layout) {
  if (!supportsColumnMode(layout)) {
    return "single";
  }
  return COLUMN_MODE_OPTIONS.includes(value) ? value : "single";
}
function parseBoolean(value, fallback) {
  if (typeof value === "boolean") {
    return value;
  }
  if (typeof value === "string") {
    if (value.toLowerCase() === "true") {
      return true;
    }
    if (value.toLowerCase() === "false") {
      return false;
    }
  }
  return fallback;
}
function readString(value) {
  return typeof value === "string" && value.trim() ? value.trim() : null;
}
function stripFrontmatter(markdown) {
  return markdown.replace(/^---\r?\n[\s\S]*?\r?\n---\r?\n?/, "");
}
function extractFirstLevelOneHeading(markdown) {
  return extractHeadings(markdown).find((heading) => heading.level === 1) ?? null;
}
function stripLeadingTitleHeading(markdown, title) {
  const lines = markdown.split(/\r?\n/);
  let inFence = false;
  const output = [];
  let removedTitle = false;
  let seenMeaningfulContent = false;
  for (const line of lines) {
    const trimmed = line.trim();
    if (/^```/.test(trimmed)) {
      inFence = !inFence;
    }
    if (!removedTitle && !inFence && !seenMeaningfulContent && trimmed.length > 0 && /^#\s+/.test(trimmed)) {
      const headingText = trimmed.replace(/^#\s+/, "").trim();
      if (!title || headingText === title) {
        removedTitle = true;
        continue;
      }
    }
    if (removedTitle && output.length === 0 && trimmed === "") {
      continue;
    }
    output.push(line);
    if (trimmed.length > 0) {
      seenMeaningfulContent = true;
    }
  }
  return output.join("\n");
}
function extractHeadings(markdown) {
  const lines = markdown.split(/\r?\n/);
  const headings = [];
  let inFence = false;
  for (const line of lines) {
    const trimmed = line.trim();
    if (/^```/.test(trimmed)) {
      inFence = !inFence;
      continue;
    }
    if (inFence) {
      continue;
    }
    const match = trimmed.match(/^(#{1,6})\s+(.+?)\s*#*\s*$/);
    if (!match) {
      continue;
    }
    headings.push({
      level: match[1].length,
      text: match[2].trim()
    });
  }
  return headings;
}
function assignAnchors(headings) {
  const seen = /* @__PURE__ */ new Map();
  return headings.map((heading) => {
    const base = toAsciiSlug(heading.text) || "section";
    const count = seen.get(base) ?? 0;
    seen.set(base, count + 1);
    return {
      level: heading.level,
      text: heading.text,
      anchor: count === 0 ? base : `${base}-${count + 1}`
    };
  });
}
function splitMarkdownIntoCards(markdown) {
  if (hasHeadingLevel(markdown, 2)) {
    return splitByHeadingLevel(markdown, 2).map((section) => ({ markdown: section.trim() })).filter((section) => section.markdown.length > 0);
  }
  return splitByBlankLines(markdown).map((section) => ({ markdown: section.trim() })).filter((section) => section.markdown.length > 0);
}
function hasHeadingLevel(markdown, level) {
  const lines = markdown.split(/\r?\n/);
  const marker = "#".repeat(level);
  let inFence = false;
  for (const line of lines) {
    const trimmed = line.trim();
    if (/^```/.test(trimmed)) {
      inFence = !inFence;
      continue;
    }
    if (!inFence && trimmed.startsWith(`${marker} `)) {
      return true;
    }
  }
  return false;
}
function splitByHeadingLevel(markdown, level) {
  const lines = markdown.split(/\r?\n/);
  const sections = [];
  const marker = "#".repeat(level);
  let current = [];
  let inFence = false;
  for (const line of lines) {
    const trimmed = line.trim();
    if (/^```/.test(trimmed)) {
      inFence = !inFence;
    }
    if (!inFence && trimmed.startsWith(`${marker} `) && current.length > 0) {
      sections.push(current.join("\n"));
      current = [];
    }
    current.push(line);
  }
  if (current.length > 0) {
    sections.push(current.join("\n"));
  }
  return sections.filter((section) => section.trim().length > 0);
}
function splitByBlankLines(markdown) {
  const lines = markdown.split(/\r?\n/);
  const sections = [];
  let current = [];
  let inFence = false;
  for (const line of lines) {
    const trimmed = line.trim();
    if (/^```/.test(trimmed)) {
      inFence = !inFence;
    }
    if (!inFence && trimmed === "" && current.length > 0) {
      sections.push(current.join("\n"));
      current = [];
      continue;
    }
    if (trimmed === "" && current.length === 0) {
      continue;
    }
    current.push(line);
  }
  if (current.length > 0) {
    sections.push(current.join("\n"));
  }
  return sections;
}
function extractImageReferences(markdown) {
  const references = [];
  markdown.replace(/!\[\[([^\]]+)\]\]/g, (_match, inner) => {
    references.push(parseWikiTarget(inner).target);
    return "";
  });
  markdown.replace(/!\[[^\]]*\]\(([^)]+)\)/g, (_match, target) => {
    references.push(parseMarkdownTarget(target));
    return "";
  });
  return references;
}
function resolveResourceReference(app, file, reference, kind) {
  const cleanedReference = reference.trim();
  if (!cleanedReference) {
    return null;
  }
  if (isExternalUrl(cleanedReference)) {
    return {
      kind,
      reference: cleanedReference,
      isExternal: true,
      externalUrl: cleanedReference
    };
  }
  const wikiTarget = parseWikiTarget(cleanedReference).target;
  const markdownTarget = parseMarkdownTarget(wikiTarget);
  const target = markdownTarget.split("?")[0];
  const resolved = app.metadataCache.getFirstLinkpathDest(target, file.path) ?? resolveViaRelativePath(app, file, target);
  if (!(resolved instanceof import_obsidian.TFile)) {
    return null;
  }
  if (!hasImageExtension(resolved.path)) {
    return null;
  }
  return {
    kind,
    reference: cleanedReference,
    isExternal: false,
    resolvedFile: resolved,
    resolvedPath: resolved.path
  };
}
function resolveViaRelativePath(app, file, reference) {
  const normalized = reference.startsWith("/") ? (0, import_obsidian.normalizePath)(reference.slice(1)) : (0, import_obsidian.normalizePath)(`${parentPath(file.path)}/${reference}`);
  const abstractFile = app.vault.getAbstractFileByPath(normalized);
  return abstractFile instanceof import_obsidian.TFile ? abstractFile : null;
}
function parseWikiTarget(raw) {
  const [targetPart, aliasPart] = raw.split("|");
  return {
    target: (targetPart ?? "").split("#")[0].trim(),
    alias: aliasPart?.trim() || void 0
  };
}
function parseMarkdownTarget(raw) {
  const trimmed = raw.trim();
  if (trimmed.startsWith("<") && trimmed.endsWith(">")) {
    return trimmed.slice(1, -1);
  }
  const titleMatch = trimmed.match(/^(.+?)(?:\s+"[^"]*")$/);
  return (titleMatch?.[1] ?? trimmed).trim();
}
function hasImageExtension(path) {
  const ext = path.split(".").pop()?.toLowerCase();
  return !!ext && IMAGE_EXTENSIONS.has(ext);
}
function isExternalUrl(value) {
  return /^(https?:\/\/|data:)/i.test(value);
}
function parentPath(path) {
  const normalized = path.replace(/\\/g, "/");
  const segments = normalized.split("/");
  segments.pop();
  return segments.join("/");
}
function makeAssetFileName(path) {
  const normalized = path.replace(/\\/g, "/");
  const baseName = normalized.split("/").pop() ?? "asset";
  const stem = baseName.replace(/\.[^.]+$/, "");
  const ext = baseName.includes(".") ? `.${baseName.split(".").pop()}` : "";
  const readable = toAsciiSlug(stem) || "asset";
  const hash = Buffer.from(normalized, "utf8").toString("base64url").slice(0, 8);
  return `${readable}-${hash}${ext.toLowerCase()}`;
}
function toAsciiSlug(value) {
  return value.toLowerCase().normalize("NFKD").replace(/[^\x00-\x7F]/g, "").replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "");
}
function estimateReadableUnits(markdown) {
  const stripped = markdown.replace(/```[\s\S]*?```/g, " ").replace(/`[^`]+`/g, " ").replace(/!\[[^\]]*\]\([^)]+\)/g, " ").replace(/!\[\[[^\]]+\]\]/g, " ").replace(/\[\[([^\]]+)\]\]/g, " $1 ").replace(/\[[^\]]+\]\([^)]+\)/g, " ").replace(/[#>*_\-\n\r]/g, " ").trim();
  const hanCount = (stripped.match(/[\p{Script=Han}]/gu) ?? []).length;
  const latinWordCount = (stripped.match(/[A-Za-z0-9]+(?:[-'][A-Za-z0-9]+)*/g) ?? []).length;
  return Math.max(1, hanCount + latinWordCount);
}
function formatUpdatedAt(timestamp) {
  return new Intl.DateTimeFormat("zh-CN", {
    year: "numeric",
    month: "2-digit",
    day: "2-digit"
  }).format(new Date(timestamp));
}

// src/exporter.ts
var import_obsidian3 = require("obsidian");

// src/render.ts
var import_obsidian2 = require("obsidian");
async function renderPrettyReaderDocument(options) {
  const { app, component, containerEl, prettyDocument, mode } = options;
  containerEl.empty();
  const root = containerEl.createDiv({
    cls: [
      "pretty-reader",
      `pretty-reader--${prettyDocument.layout}`,
      `pretty-reader-columns--${prettyDocument.columnMode}`,
      `pretty-reader-theme--${prettyDocument.theme}`
    ].join(" ")
  });
  if (prettyDocument.cover) {
    root.addClass("has-cover");
  }
  const shell = root.createDiv({ cls: "pretty-reader-shell" });
  renderHeader(app, shell, prettyDocument, mode);
  const body = shell.createDiv({ cls: "pretty-reader-body" });
  const content = body.createDiv({ cls: "pretty-reader-content" });
  const renderedHeadings = prettyDocument.layout === "cards" ? await renderCards(app, content, component, prettyDocument, mode) : await renderMarkdownBlock(
    app,
    content,
    component,
    mode === "export" ? prettyDocument.exportMarkdown : prettyDocument.displayMarkdown,
    prettyDocument.filePath,
    prettyDocument
  );
  if (prettyDocument.toc && renderedHeadings.length > 0) {
    body.addClass("has-toc");
    const toc = createToc(renderedHeadings, body, mode);
    body.appendChild(toc);
  }
}
function renderHeader(app, containerEl, prettyDocument, mode) {
  const coverUrl = getCoverUrl(app, prettyDocument, mode);
  const header = containerEl.createDiv({ cls: "pretty-reader-header" });
  const main = header.createDiv({ cls: "pretty-reader-header-main" });
  if (coverUrl) {
    const cover = main.createDiv({ cls: "pretty-reader-cover" });
    cover.createEl("img", {
      attr: {
        alt: `${prettyDocument.title} cover`,
        src: coverUrl
      }
    });
  }
  const intro = main.createDiv({ cls: "pretty-reader-intro" });
  const eyebrowRow = intro.createDiv({ cls: "pretty-reader-eyebrow-row" });
  eyebrowRow.createEl("p", {
    cls: "pretty-reader-eyebrow",
    text: prettyDocument.layout
  });
  eyebrowRow.createSpan({
    cls: "pretty-reader-divider-dot",
    text: "|"
  });
  eyebrowRow.createSpan({
    cls: "pretty-reader-updated",
    text: `Updated ${prettyDocument.updatedLabel}`
  });
  intro.createEl("h1", {
    cls: "pretty-reader-title",
    text: prettyDocument.title
  });
  if (prettyDocument.subtitle) {
    intro.createEl("p", {
      cls: "pretty-reader-subtitle",
      text: prettyDocument.subtitle
    });
  }
  const meta = intro.createDiv({ cls: "pretty-reader-meta" });
  if (prettyDocument.author) {
    meta.createSpan({
      cls: "pretty-reader-meta-pill",
      text: prettyDocument.author
    });
  }
  const summaryBar = intro.createDiv({ cls: "pretty-reader-summary-bar" });
  renderSummaryItem(summaryBar, "Read", `${prettyDocument.readingMinutes} min`);
  renderSummaryItem(
    summaryBar,
    "Words",
    prettyDocument.wordCount.toLocaleString("zh-CN")
  );
  renderSummaryItem(summaryBar, "Theme", prettyDocument.theme);
  renderSummaryItem(
    summaryBar,
    supportsColumnMode(prettyDocument.layout) ? "Columns" : "Layout",
    supportsColumnMode(prettyDocument.layout) ? prettyDocument.columnMode : prettyDocument.layout
  );
}
async function renderCards(app, containerEl, component, prettyDocument, mode) {
  const cardsGrid = containerEl.createDiv({ cls: "pretty-reader-cards-grid" });
  const cards = mode === "export" ? prettyDocument.exportCards : prettyDocument.cards;
  for (const card of cards) {
    const cardEl = cardsGrid.createDiv({ cls: "pretty-reader-card" });
    await renderMarkdownBlock(
      app,
      cardEl,
      component,
      card.markdown,
      prettyDocument.filePath,
      prettyDocument
    );
  }
  return assignHeadingAnchors(cardsGrid);
}
async function renderMarkdownBlock(app, containerEl, component, markdown, sourcePath, prettyDocument) {
  containerEl.addClass("pretty-reader-prose", "markdown-rendered");
  await import_obsidian2.MarkdownRenderer.render(app, markdown, containerEl, sourcePath, component);
  enrichRichBlocks(containerEl);
  applyColumnLayout(containerEl, prettyDocument);
  return assignHeadingAnchors(containerEl);
}
function assignHeadingAnchors(containerEl) {
  const headings = [];
  const seen = /* @__PURE__ */ new Map();
  const headingEls = containerEl.querySelectorAll(
    "h1, h2, h3, h4, h5, h6"
  );
  for (const headingEl of headingEls) {
    const text = headingEl.innerText.trim();
    if (!text) {
      continue;
    }
    const base = slugifyHeading(text) || "section";
    const count = seen.get(base) ?? 0;
    seen.set(base, count + 1);
    const anchor = count === 0 ? base : `${base}-${count + 1}`;
    headingEl.id = anchor;
    headings.push({
      level: Number(headingEl.tagName.slice(1)),
      text,
      anchor
    });
  }
  return headings;
}
function createToc(headings, bodyEl, mode) {
  const toc = document.createElement("aside");
  toc.className = "pretty-reader-toc";
  const title = document.createElement("h2");
  title.className = "pretty-reader-toc-title";
  title.textContent = "On this page";
  toc.appendChild(title);
  const list = document.createElement("ul");
  list.className = "pretty-reader-toc-list";
  for (const heading of headings) {
    const item = document.createElement("li");
    item.className = `pretty-reader-toc-item level-${heading.level}`;
    const link = document.createElement("a");
    link.href = `#${heading.anchor}`;
    link.textContent = heading.text;
    if (mode === "view") {
      link.addEventListener("click", (event) => {
        event.preventDefault();
        const target = bodyEl.querySelector(`#${heading.anchor}`);
        target?.scrollIntoView({
          behavior: "smooth",
          block: "start"
        });
      });
    }
    item.appendChild(link);
    list.appendChild(item);
  }
  toc.appendChild(list);
  return toc;
}
function getCoverUrl(app, prettyDocument, mode) {
  const cover = prettyDocument.cover;
  if (!cover) {
    return null;
  }
  if (cover.isExternal) {
    return cover.externalUrl ?? null;
  }
  if (!cover.resolvedFile) {
    return null;
  }
  if (mode === "view") {
    return app.vault.getResourcePath(cover.resolvedFile);
  }
  return assetExportHref(cover);
}
function renderSummaryItem(containerEl, label, value) {
  const item = containerEl.createDiv({ cls: "pretty-reader-summary-item" });
  item.createSpan({
    cls: "pretty-reader-summary-label",
    text: label
  });
  item.createSpan({
    cls: "pretty-reader-summary-value",
    text: value
  });
}
function enrichRichBlocks(containerEl) {
  for (const blockquote of containerEl.querySelectorAll("blockquote")) {
    blockquote.addClass("pretty-reader-quote-block");
  }
  for (const callout of containerEl.querySelectorAll(".callout")) {
    callout.addClass("pretty-reader-callout");
  }
  for (const mathBlock of containerEl.querySelectorAll(
    ".math.math-block, mjx-container[display='true']"
  )) {
    mathBlock.addClass("pretty-reader-math-block");
  }
  for (const footnotes of containerEl.querySelectorAll(".footnotes")) {
    footnotes.addClass("pretty-reader-footnotes");
  }
}
function applyColumnLayout(containerEl, prettyDocument) {
  if (prettyDocument.columnMode !== "double" || !supportsColumnMode(prettyDocument.layout)) {
    return;
  }
  const topLevelBlocks = Array.from(containerEl.children).filter(
    (child) => child instanceof HTMLElement
  );
  if (topLevelBlocks.length === 0) {
    return;
  }
  const fragment = containerEl.ownerDocument.createDocumentFragment();
  let flow = createColumnFlow(containerEl.ownerDocument);
  const flushFlow = () => {
    if (flow.childElementCount === 0) {
      return;
    }
    fragment.appendChild(flow);
    flow = createColumnFlow(containerEl.ownerDocument);
  };
  for (const block of topLevelBlocks) {
    decorateColumnBlock(block);
    if (shouldSpanAllBlock(block)) {
      flushFlow();
      block.addClass("pretty-reader-span-all");
      fragment.appendChild(block);
      continue;
    }
    block.addClass("pretty-reader-column-item");
    flow.appendChild(block);
  }
  flushFlow();
  if (fragment.childNodes.length > 0) {
    containerEl.replaceChildren(fragment);
  }
}
function createColumnFlow(doc) {
  const flow = doc.createElement("div");
  flow.className = "pretty-reader-column-flow";
  return flow;
}
function decorateColumnBlock(block) {
  if (isStandaloneEmphasisBlock(block)) {
    block.addClass("pretty-reader-standalone-emphasis");
  }
}
function shouldSpanAllBlock(block) {
  if (matchesSpanAllBlock(block) || isStandaloneEmphasisBlock(block)) {
    return true;
  }
  const directChildren = Array.from(block.children).filter(
    (child) => child instanceof HTMLElement
  );
  if (directChildren.length === 1 && matchesSpanAllBlock(directChildren[0])) {
    return true;
  }
  if (block.matches("p, div") && block.querySelector("img, .internal-embed")) {
    return true;
  }
  return false;
}
function isStandaloneEmphasisBlock(block) {
  if (!block.matches("p, div")) {
    return false;
  }
  const elementChildren = Array.from(block.children).filter(
    (child) => child instanceof HTMLElement
  );
  if (elementChildren.length !== 1) {
    return false;
  }
  const emphasisEl = elementChildren[0];
  if (!emphasisEl.matches("strong, b, em")) {
    return false;
  }
  for (const node of Array.from(block.childNodes)) {
    if (node === emphasisEl) {
      continue;
    }
    if (node.nodeType === Node.TEXT_NODE && node.textContent?.trim()) {
      return false;
    }
    if (node.nodeType === Node.ELEMENT_NODE) {
      return false;
    }
  }
  const text = emphasisEl.textContent?.trim() ?? "";
  return text.length >= 10;
}
function matchesSpanAllBlock(block) {
  return block.matches(
    [
      "h1",
      "h2",
      "h3",
      "h4",
      "h5",
      "h6",
      "pre",
      "table",
      "hr",
      ".callout",
      ".pretty-reader-callout",
      ".math.math-block",
      ".pretty-reader-math-block",
      "mjx-container[display='true']",
      ".pretty-reader-footnotes",
      ".footnotes"
    ].join(", ")
  );
}
function slugifyHeading(value) {
  return value.toLowerCase().normalize("NFKD").replace(/[^\x00-\x7F]/g, "").replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "");
}

// src/exporter.ts
var EXTRA_EXPORT_CSS = `
body {
  margin: 0;
  background: #f4efe4;
}

img {
  max-width: 100%;
}
`;
async function exportPrettyReaderHtml(options) {
  const { app, exportRoot, prettyDocument } = options;
  const slug = noteSlug(prettyDocument.filePath);
  const outputPath = (0, import_obsidian3.normalizePath)(`${exportRoot}/${slug}`);
  const assetsPath = (0, import_obsidian3.normalizePath)(`${outputPath}/assets`);
  await ensureFolder(app, assetsPath);
  await copyLocalAssets(app, prettyDocument.resources, assetsPath);
  const tempComponent = new import_obsidian3.Component();
  const tempContainer = document.createElement("div");
  await renderPrettyReaderDocument({
    app,
    component: tempComponent,
    containerEl: tempContainer,
    prettyDocument,
    mode: "export"
  });
  await waitForRichRender();
  const styles = await loadPluginStyles(app);
  const html = buildHtmlDocument(prettyDocument.title, tempContainer.innerHTML, styles);
  await app.vault.adapter.write((0, import_obsidian3.normalizePath)(`${outputPath}/index.html`), html);
  tempComponent.unload();
  return {
    outputPath: (0, import_obsidian3.normalizePath)(`${outputPath}/index.html`)
  };
}
async function copyLocalAssets(app, resources, assetsPath) {
  const copied = /* @__PURE__ */ new Set();
  for (const resource of resources) {
    if (resource.isExternal || !resource.resolvedPath || !resource.assetFileName) {
      continue;
    }
    if (copied.has(resource.resolvedPath)) {
      continue;
    }
    const binary = await app.vault.adapter.readBinary(resource.resolvedPath);
    await app.vault.adapter.writeBinary(
      (0, import_obsidian3.normalizePath)(`${assetsPath}/${resource.assetFileName}`),
      binary
    );
    copied.add(resource.resolvedPath);
  }
}
async function loadPluginStyles(app) {
  const pluginStylesPath = ".obsidian/plugins/pretty-reader/styles.css";
  const stylesheet = await app.vault.adapter.read(pluginStylesPath);
  const runtimeStyles = loadRuntimeMathStyles();
  return `${stylesheet}
${runtimeStyles}
${EXTRA_EXPORT_CSS}`;
}
function buildHtmlDocument(title, bodyMarkup, styles) {
  return `<!doctype html>
<html lang="zh-CN">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>${escapeHtml(title)}</title>
    <style>
${styles}
    </style>
  </head>
  <body class="pretty-reader-export">
${bodyMarkup}
  </body>
</html>
`;
}
function escapeHtml(value) {
  return value.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}
async function waitForRichRender() {
  await new Promise((resolve) => {
    window.setTimeout(() => resolve(), 50);
  });
}
function loadRuntimeMathStyles() {
  const styleEls = Array.from(
    document.querySelectorAll(
      "#MJX-CHTML-styles, style[id^='MJX-']"
    )
  );
  return styleEls.map((styleEl) => styleEl.textContent ?? "").join("\n");
}

// main.ts
var PrettyReaderView = class extends import_obsidian4.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.state = {};
    this.plugin = plugin;
    this.navigation = true;
  }
  getViewType() {
    return PRETTY_READER_VIEW_TYPE;
  }
  getDisplayText() {
    if (!this.state.file) {
      return "Pretty Reader";
    }
    const abstractFile = this.app.vault.getAbstractFileByPath(this.state.file);
    if (abstractFile instanceof import_obsidian4.TFile) {
      return `${abstractFile.basename} | Pretty Reader`;
    }
    return "Pretty Reader";
  }
  getIcon() {
    return "book-open";
  }
  getState() {
    return this.state;
  }
  async setState(state, result) {
    this.state = {
      file: state.file
    };
    await this.renderView();
    return super.setState(state, result);
  }
  async onOpen() {
    this.contentEl.addClass("pretty-reader-view");
    this.contentEl.setAttribute("tabindex", "0");
    this.registerDomEvent(this.contentEl, "contextmenu", (event) => {
      this.handleContextMenu(event);
    });
    this.registerEvent(
      this.app.vault.on("modify", (file) => {
        if (file instanceof import_obsidian4.TFile && file.path === this.state.file) {
          void this.renderView();
        }
      })
    );
    this.registerEvent(
      this.app.vault.on("rename", (file, oldPath) => {
        if (file instanceof import_obsidian4.TFile && this.state.file === oldPath) {
          this.state.file = file.path;
          void this.renderView();
        }
      })
    );
    this.registerEvent(
      this.app.vault.on("delete", (file) => {
        if (file instanceof import_obsidian4.TFile && file.path === this.state.file) {
          void this.renderEmpty("The source note was deleted.");
        }
      })
    );
    await this.renderView();
  }
  async renderView() {
    this.contentEl.empty();
    if (!this.state.file) {
      await this.renderEmpty("Open a Markdown note to start Pretty Reader.");
      return;
    }
    const abstractFile = this.app.vault.getAbstractFileByPath(this.state.file);
    if (!(abstractFile instanceof import_obsidian4.TFile)) {
      await this.renderEmpty("The selected note is no longer available.");
      return;
    }
    const prettyDocument = await buildPrettyReaderDocument(
      this.app,
      abstractFile,
      this.plugin.settings
    );
    this.currentDocument = prettyDocument;
    await renderPrettyReaderDocument({
      app: this.app,
      component: this,
      containerEl: this.contentEl,
      prettyDocument,
      mode: "view"
    });
  }
  async renderEmpty(message) {
    this.contentEl.empty();
    this.currentDocument = void 0;
    const emptyState = this.contentEl.createDiv({
      cls: "pretty-reader-empty-state"
    });
    emptyState.createEl("h2", { text: "Pretty Reader" });
    emptyState.createEl("p", { text: message });
  }
  handleContextMenu(event) {
    if (!this.currentDocument) {
      return;
    }
    const target = event.target;
    if (!(target instanceof Node) || !this.contentEl.contains(target)) {
      return;
    }
    event.preventDefault();
    event.stopPropagation();
    const menu = new import_obsidian4.Menu();
    const selectedText = this.getSelectedText();
    const notePreference = this.plugin.getNotePreference(this.currentDocument.filePath);
    menu.addItem((item) => {
      item.setTitle("Copy selected text").setIcon("copy").setDisabled(selectedText.length === 0).onClick(() => {
        void this.copyText(selectedText);
      });
    });
    menu.addSeparator();
    menu.addItem((item) => {
      item.setTitle("Theme").setIsLabel(true);
    });
    for (const theme of THEME_OPTIONS) {
      menu.addItem((item) => {
        item.setTitle(theme).setChecked(this.currentDocument?.theme === theme).onClick(() => {
          void this.plugin.setNoteTheme(this.currentDocument.filePath, theme);
        });
      });
    }
    menu.addItem((item) => {
      item.setTitle("Reset theme").setIcon("rotate-ccw").setDisabled(!notePreference.theme).onClick(() => {
        void this.plugin.resetNoteTheme(this.currentDocument.filePath);
      });
    });
    menu.addSeparator();
    menu.addItem((item) => {
      item.setTitle("Column mode").setIsLabel(true);
    });
    if (!supportsColumnMode(this.currentDocument.layout)) {
      menu.addItem((item) => {
        item.setTitle("Dual column unavailable for cards").setDisabled(true);
      });
    } else {
      for (const columnMode of COLUMN_MODE_OPTIONS) {
        menu.addItem((item) => {
          item.setTitle(
            columnMode === "single" ? "Single column" : "Dual column"
          ).setChecked(this.currentDocument?.columnMode === columnMode).onClick(() => {
            void this.plugin.setNoteColumnMode(
              this.currentDocument.filePath,
              columnMode
            );
          });
        });
      }
    }
    menu.showAtMouseEvent(event);
  }
  getSelectedText() {
    const selection = this.contentEl.ownerDocument.getSelection();
    if (!selection || selection.isCollapsed) {
      return "";
    }
    const anchorNode = selection.anchorNode;
    const focusNode = selection.focusNode;
    if (!anchorNode || !focusNode) {
      return "";
    }
    if (!this.contentEl.contains(anchorNode) || !this.contentEl.contains(focusNode)) {
      return "";
    }
    return selection.toString().trim();
  }
  async copyText(text) {
    if (!text) {
      return;
    }
    try {
      if (navigator.clipboard?.writeText) {
        await navigator.clipboard.writeText(text);
      } else if (!this.fallbackCopyText(text)) {
        throw new Error("Clipboard API unavailable");
      }
      new import_obsidian4.Notice("Selected text copied.");
    } catch {
      if (this.fallbackCopyText(text)) {
        new import_obsidian4.Notice("Selected text copied.");
      } else {
        new import_obsidian4.Notice("Unable to copy selected text.");
      }
    }
  }
  fallbackCopyText(text) {
    const doc = this.contentEl.ownerDocument;
    const textarea = doc.createElement("textarea");
    textarea.value = text;
    textarea.setAttribute("readonly", "true");
    textarea.style.position = "fixed";
    textarea.style.opacity = "0";
    textarea.style.pointerEvents = "none";
    doc.body.appendChild(textarea);
    textarea.select();
    textarea.setSelectionRange(0, textarea.value.length);
    const copied = doc.execCommand("copy");
    textarea.remove();
    return copied;
  }
};
var PrettyReaderPlugin = class extends import_obsidian4.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
  }
  async onload() {
    await this.loadSettings();
    this.registerEvent(
      this.app.vault.on("rename", (file, oldPath) => {
        if (file instanceof import_obsidian4.TFile) {
          void this.handleFileRename(oldPath, file.path);
        }
      })
    );
    this.registerEvent(
      this.app.vault.on("delete", (file) => {
        if (file instanceof import_obsidian4.TFile) {
          void this.handleFileDelete(file.path);
        }
      })
    );
    const ribbonIconEl = this.addRibbonIcon(
      "book-open",
      "Open Pretty Reader",
      () => {
        void this.openPrettyReader();
      }
    );
    ribbonIconEl.addClass("pretty-reader-ribbon-button");
    this.registerView(
      PRETTY_READER_VIEW_TYPE,
      (leaf) => new PrettyReaderView(leaf, this)
    );
    this.addCommand({
      id: "open-pretty-reader",
      name: "Open Pretty Reader",
      callback: () => {
        void this.openPrettyReader();
      }
    });
    this.addCommand({
      id: "export-pretty-reader-html",
      name: "Export Pretty Reader HTML",
      callback: () => {
        void this.exportActiveNote();
      }
    });
    this.addSettingTab(new PrettyReaderSettingTab(this.app, this));
  }
  async onunload() {
    this.app.workspace.detachLeavesOfType(PRETTY_READER_VIEW_TYPE);
  }
  async loadSettings() {
    const loaded = await this.loadData();
    this.settings = {
      ...DEFAULT_SETTINGS,
      ...loaded,
      defaultLayout: this.parseLayoutValue(loaded?.defaultLayout),
      defaultTheme: this.parseThemeValue(loaded?.defaultTheme),
      exportDirectory: normalizeExportDirectory(
        loaded?.exportDirectory ?? DEFAULT_SETTINGS.exportDirectory
      ),
      notePreferences: this.normalizeNotePreferences(loaded?.notePreferences)
    };
  }
  async saveSettings() {
    this.settings.exportDirectory = normalizeExportDirectory(
      this.settings.exportDirectory
    );
    this.settings.notePreferences = this.normalizeNotePreferences(
      this.settings.notePreferences
    );
    await this.saveData(this.settings);
    await this.rerenderPrettyReaderLeaves();
  }
  parseLayoutValue(value) {
    return LAYOUT_OPTIONS.includes(value) ? value : DEFAULT_SETTINGS.defaultLayout;
  }
  parseThemeValue(value) {
    return THEME_OPTIONS.includes(value) ? value : DEFAULT_SETTINGS.defaultTheme;
  }
  normalizeNotePreferences(value) {
    if (!value || typeof value !== "object") {
      return {};
    }
    const normalized = {};
    for (const [filePath, preference] of Object.entries(
      value
    )) {
      if (!preference || typeof preference !== "object") {
        continue;
      }
      const nextPreference = {};
      const rawTheme = preference.theme;
      const rawColumnMode = preference.columnMode;
      if (THEME_OPTIONS.includes(rawTheme)) {
        nextPreference.theme = rawTheme;
      }
      if (COLUMN_MODE_OPTIONS.includes(rawColumnMode)) {
        nextPreference.columnMode = rawColumnMode;
      }
      if (nextPreference.theme || nextPreference.columnMode) {
        normalized[filePath] = nextPreference;
      }
    }
    return normalized;
  }
  getActiveMarkdownFile() {
    const file = this.app.workspace.getActiveFile();
    if (!file || file.extension !== "md") {
      return null;
    }
    return file;
  }
  async openPrettyReader() {
    const file = this.getActiveMarkdownFile();
    if (!file) {
      new import_obsidian4.Notice("Open a Markdown note before launching Pretty Reader.");
      return;
    }
    const existingLeaf = this.findPrettyReaderLeaf(file.path);
    const leaf = existingLeaf ?? this.app.workspace.getLeaf("tab");
    await leaf.setViewState({
      type: PRETTY_READER_VIEW_TYPE,
      active: true,
      state: {
        file: file.path
      }
    });
    this.app.workspace.revealLeaf(leaf);
  }
  findPrettyReaderLeaf(filePath) {
    for (const leaf of this.app.workspace.getLeavesOfType(
      PRETTY_READER_VIEW_TYPE
    )) {
      if (!(leaf.view instanceof PrettyReaderView)) {
        continue;
      }
      if (leaf.view.getState().file === filePath) {
        return leaf;
      }
    }
    return null;
  }
  getNotePreference(filePath) {
    return this.settings.notePreferences[filePath] ?? {};
  }
  async setNoteTheme(filePath, theme) {
    const nextPreference = {
      ...this.getNotePreference(filePath),
      theme
    };
    await this.setNotePreference(filePath, nextPreference);
  }
  async resetNoteTheme(filePath) {
    const nextPreference = {
      ...this.getNotePreference(filePath)
    };
    delete nextPreference.theme;
    await this.setNotePreference(filePath, nextPreference);
  }
  async setNoteColumnMode(filePath, columnMode) {
    const nextPreference = {
      ...this.getNotePreference(filePath),
      columnMode
    };
    await this.setNotePreference(filePath, nextPreference);
  }
  async setNotePreference(filePath, preference) {
    if (preference.theme || preference.columnMode) {
      this.settings.notePreferences[filePath] = preference;
    } else {
      delete this.settings.notePreferences[filePath];
    }
    await this.saveSettings();
  }
  async handleFileRename(oldPath, newPath) {
    if (oldPath === newPath) {
      return;
    }
    const existingPreference = this.settings.notePreferences[oldPath];
    if (!existingPreference) {
      return;
    }
    delete this.settings.notePreferences[oldPath];
    this.settings.notePreferences[newPath] = existingPreference;
    await this.saveSettings();
  }
  async handleFileDelete(filePath) {
    if (!this.settings.notePreferences[filePath]) {
      return;
    }
    delete this.settings.notePreferences[filePath];
    await this.saveSettings();
  }
  async exportActiveNote() {
    const file = this.getActiveMarkdownFile();
    if (!file) {
      new import_obsidian4.Notice("Open a Markdown note before exporting Pretty Reader HTML.");
      return;
    }
    const prettyDocument = await buildPrettyReaderDocument(
      this.app,
      file,
      this.settings
    );
    const result = await exportPrettyReaderHtml({
      app: this.app,
      exportRoot: this.settings.exportDirectory,
      prettyDocument
    });
    new import_obsidian4.Notice(`Pretty Reader exported to ${result.outputPath}`);
  }
  async rerenderPrettyReaderLeaves() {
    const leaves = this.app.workspace.getLeavesOfType(PRETTY_READER_VIEW_TYPE);
    await Promise.all(
      leaves.map(async (leaf) => {
        if (leaf.view instanceof PrettyReaderView) {
          await leaf.view.renderView();
        }
      })
    );
  }
};
var PrettyReaderSettingTab = class extends import_obsidian4.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Pretty Reader" });
    new import_obsidian4.Setting(containerEl).setName("Default layout").setDesc("Applied when a note does not define pretty in frontmatter.").addDropdown((dropdown) => {
      for (const layout of LAYOUT_OPTIONS) {
        dropdown.addOption(layout, layout);
      }
      dropdown.setValue(this.plugin.settings.defaultLayout);
      dropdown.onChange(async (value) => {
        this.plugin.settings.defaultLayout = value;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian4.Setting(containerEl).setName("Default theme").setDesc("Applied when a note does not define theme in frontmatter.").addDropdown((dropdown) => {
      for (const theme of THEME_OPTIONS) {
        dropdown.addOption(theme, theme);
      }
      dropdown.setValue(this.plugin.settings.defaultTheme);
      dropdown.onChange(async (value) => {
        this.plugin.settings.defaultTheme = value;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian4.Setting(containerEl).setName("Export directory").setDesc("Exported HTML is written beneath the vault root.").addText((text) => {
      text.setPlaceholder(DEFAULT_SETTINGS.exportDirectory);
      text.setValue(this.plugin.settings.exportDirectory);
      text.onChange(async (value) => {
        this.plugin.settings.exportDirectory = (0, import_obsidian4.normalizePath)(
          value || DEFAULT_SETTINGS.exportDirectory
        );
        await this.plugin.saveSettings();
      });
    });
  }
};
